### ISSUE TITLE
Transfer tasks

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.ciscosmb#25]
- [x] Transfer repo
- [x] Update galaxy.yml and other documentation to refer to new name
- [x] Update [workflows](https://github.com/ansible-collections/community.ciscosmb/tree/main/.github/workflows) to use new collection name
- [x] Add Zuul to publish collection to galaxy under the community namespace (@gundalow)
- [x] Add other maintainers, who needs adding?
- [x] Publish final update to original collection with updated README.md pointing to this new collection
- [x] Deprecate old collection in Galaxy UI

**Comment by qaxi** [comment]
Hello @gundalow,
I am stuck in sanity tests.

See https://github.com/ansible-collections/community.ciscosmb/runs/2304480423?check_suite_focus=true

Test is complaining about:
plugins/module_utils/ciscosmb.py:37:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'

In my collection i specified (galaxy.yml) that "ansible.netcommon" is required dependency.

It seems that ansible-test --docker sanity, did not install dependency in this case Ansible Galaxy collection "ansible.netcommon".

I do something wrong but I do not know what. Can you help me?

**Comment by gundalow** [comment]
> Hello @gundalow,
> I am stuck in sanity tests.
> 
> See https://github.com/ansible-collections/community.ciscosmb/runs/2304480423?check_suite_focus=true
> 
> Test is complaining about:
> plugins/module_utils/ciscosmb.py:37:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'
> 
> In my collection i specified (galaxy.yml) that "ansible.netcommon" is required dependency.
> 
> It seems that ansible-test --docker sanity, did not install dependency in this case Ansible Galaxy collection "ansible.netcommon".
> 
> I do something wrong but I do not know what. Can you help me?

@qaxi I can help with this. I know it's a bit tricky get get the CI working initially. I'll work on getting CI green in 

https://github.com/ansible-collections/community.ciscosmb/pull/26/



@qaxi Could you help me understand what these [GitHub Action workflow files](https://github.com/ansible-collections/community.ciscosmb/tree/main/.github/workflows) are for
ansible-manual-sanity-tests.yml
ansible-manual-unit-tests.yml
ansible-collection-tests.yml
ansible-tests-fast.yml

**Comment by qaxi** [comment]
> @qaxi Could you help me understand what these GitHub Action workflow files are for
ansible-manual-sanity-tests.yml
ansible-manual-unit-tests.yml
ansible-collection-tests.yml
ansible-tests-fast.yml

Those are tests I wrote for testing "by hand".
It all will be deleted and only "ansible-collection-tests.yml" will stay as standard Ansible collection test.

The only thing I am unsure is "ansible-galaxy-deploy.yml" for deploying to Galaxy, but is suppose "Add Zuul to publish collection" in task list will solve my concerns .

**Comment by qaxi** [comment]
There are on other maintainers at the time.

**Comment by qaxi** [comment]
Hello @gundalow.
By e810e5a I prepared old collection "qaxi.ciscosmb" for deploying v.0.9.2 to Ansible Galaxy - first step to deprecate it.
There is deprecating notice in README.

**Comment by qaxi** [comment]
Old collection is deprecated now https://galaxy.ansible.com/qaxi/ciscosmb

**Comment by qaxi** [comment]
Hello,
is it possible to publish this package on Galaxy?  @gundalow 
The old version "qaxi.ciscosmb" is deprecated on Galaxy.

**Comment by Andersson007** [comment]
> Hello,
> is it possible to publish this package on Galaxy? @gundalow
> The old version "qaxi.ciscosmb" is deprecated on Galaxy.

I think it's just been done

**Comment by qaxi** [comment]
Thank you.

Just for clarity, when I make release, will it publish module to Ansible Galaxy?

**Comment by gundalow** [comment]
Update galaxy.yml to the next version
git tag as that release
push the tag
Then Zuul will build and publish to Galaxy

>

**Comment by qaxi** [comment]
Thank you all for help.

**Comment by Andersson007** [comment]
@qaxi https://github.com/ansible/community-docs/blob/main/releasing_collections.rst
