### ISSUE TITLE
Links at bottom of readme don't work in Galaxy

### ISSUE THREAD

**Issue by samccann** [ansible-collections/community.ciscosmb#47]
##### SUMMARY

If I go to this collection today on galaxy and scroll down to the last sections, all three links are broken when I look at this inside Galaxy.  They are currently relative links:
`See [RELEASE_POLICY.md](./RELEASE_POLICY.md)
`
And should be absolute links instead.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by qaxi** [comment]
PR #48 Released in version 1.0.4
