### ISSUE TITLE
Not saving all running config 

### ISSUE THREAD

**Issue by FilipFabicevic** [ansible-collections/community.ciscosmb#63]
##### SUMMARY
While saving running config from cisco cbs350 it only saves first 15 lines as you know you have to press space to read all the config on cisco switches. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- community.ciscosmb

##### ANSIBLE VERSION

```ansible 2.9.6
  config file = /home/ffabicevic/ansible_test/ansible.cfg
  configured module search path = ['/home/ffabicevic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
```

##### COLLECTION VERSION
```ansible-galaxy collection community.ciscosmb
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cisco CBS350-48P-PoE  ios ver: 3.2.0.84

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

##### STEPS TO REPRODUCE

Just check your cfg file it only has 15 lines. Did you'r steps same as you everything goes well but the copied .cfg file is not complete.

```- name: Gather Facts
  gather_facts: no
  hosts: all
  vars:
    - configs_dir: configs

  tasks:

    - name: Host info
      ansible.builtin.debug:
        verbosity: 3
        var: "hostvars"

    ###
    # Collect data
    #
    # - name: CiscoSMB - Gather Facts - subset default
    #  community.ciscosmb.facts:
    #    gather_subset:
    #      - default
      # when: ansible_network_os == 'community.ciscosmb.ciscosmb'

    - name: CiscoSMB - Gather Facts - subset config
      community.ciscosmb.facts:
        gather_subset:
          - config
            #      vars:
#        ansible_become: yes
#      # when: ansible_network_os == 'community.ciscosmb.ciscosmb'

    - name: CSV output
      ansible.builtin.debug:
        verbosity: 1
        msg:
          - "{{ ansible_facts['net_hostname'] }};{{ ansible_facts['net_model'] }};{{ ansible_facts['net_serialnum'] }};{{ ansible_facts['net_version'] }};{{ ansible_facts['net_hw_version'] }}"

    - name: Verbose output
      ansible.builtin.debug:
        verbosity: 2
        msg:
          - "Hostname:     {{ ansible_facts['net_hostname'] }}"
          - "Model:        {{ ansible_facts['net_model'] }}"
          - "SN:           {{ ansible_facts['net_serialnum'] }}"
          - "SW version    {{ ansible_facts['net_version'] }}"
          - "HW version:   {{ ansible_facts['net_hw_version'] }}"
          - "config:       {{ ansible_facts['net_config'] | default('') }}"

    - name: Create configuration directory
      local_action: file path={{ configs_dir }} state=directory
      run_once: true
      check_mode: no
      changed_when: no

    - name: Save running config
      local_action: copy content={{ ansible_net_config }} dest={{ configs_dir }}/{{ inventory_hostname }}_net_config

```

##### EXPECTED RESULTS

Whole running-config to be backuped.

##### ACTUAL RESULTS

The task completes.

```only saves first few lines of running config

```

**Comment by qaxi** [comment]
Hi,
currently I do not have access to Cisco CBS350 for testing.

Therre is command for forbiding paged output on terminal.

In older versions of firmware it was (you can see plugins/terminal/ciscosmb.py) "terminal datadump". 

Please test this for me (in enable mode):

```
# Does this produce paged output?
sh running-config

# Does this output any error?
terminal datadump

# Does this produce full continuous output of config
terminal datadump
sh running-config
```

**Comment by FilipFabicevic** [comment]
Seems like terminal datadump did the trick, it show all the output of a show command. :)

**Comment by qaxi** [comment]
The _terminal datadump_ should be run on shell open ... ie. you should not run it yourself, the terminal should be "preset" for you.

How exactly did you change your playbook to make it work?

**Comment by FilipFabicevic** [comment]
I made a playbook that runs basic commands without getting to execute mode. I did not use the playbook given, and also made a safer way to store configurations with scp to my ftp server and schedule a job for it.
