### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by sergioolovrap** [ansible-collections/community.ciscosmb#66]
##### SUMMARY
Can't connect to switch

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module send commands

##### ANSIBLE VERSION
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o StrictHostKeyChecking=accept-new

##### OS / ENVIRONMENT
SW version    1.4.9.4 ( date  03-Jun-2018 time  23:53:37 )
Boot version    1.4.0.02 ( date  24-Jun-2014 time  12:01:31 )

NAME: "1"   DESCR: "SG500-28P 28-Port Gigabit PoE Stackable Managed Switch"

##### STEPS TO REPRODUCE
file hosts
[SWITCH-TEST-SG500]
10.127.5.136
[SWITCH-TEST-SG500:vars]
ansible_become_method=enable
ansible_become=true
ansible_network_cli_ssh_type=paramiko
ansible_connection=network_cli
ansible_network_os=community.ciscosmb.ciscosmb
ansible_user=user
ansible_password=password

file create_snmpv2_sg500.yml
- name: Create SNMPv2 community for Cisco Small Business
  hosts: SWITCH-TEST-SG500
  gather_facts: false
  connection: local

  vars:
    community: xxxx

  tasks:
    - name: Create community "{{ community }}"
      community.ciscosmb.command:
        commands: 
          - conf t
          - snmp-server community "{{ community }}" ro

##### ACTUAL RESULTS
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.ciscosmb.command_payload_2l9h4j/ansible_community.ciscosmb.command_payload.zip/ansible_collections/community/ciscosmb/plugins/module_utils/ciscosmb.py", line 219, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_community.ciscosmb.command_payload_2l9h4j/ansible_community.ciscosmb.command_payload.zip/ansible/module_utils/connection.py", line 190, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [10.127.5.136]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "conf t",
                "snmp-server community XXXX ro"
            ],
            "interval": 1,
            "match": "all",
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "super() takes at least 1 argument (0 given)"

**Comment by qaxi** [comment]
Hello,
I can see you need "enable mode" but you do not set "ansible_become_password:" ...

```
ansible_become_method=enable
ansible_become=true
ansible_become_password: **password**
```

**Comment by sergioolovrap** [comment]
it's not needed because my user has privilege 15, but I add become_password.
Same problem

**Comment by FilipFabicevic** [comment]
enable ip ssh password-auth --> try enabling this on CIsco swithces

**Comment by qaxi** [comment]
> it's not needed because my user has privilege 15, but I add become_password. Same problem

> enable ip ssh password-auth --> try enabling this on CIsco swithces

Hi, did enabling "ip ssh password-auth" solved the problem?

**Comment by FilipFabicevic** [comment]
> > it's not needed because my user has privilege 15, but I add become_password. Same problem
> 
> > enable ip ssh password-auth --> try enabling this on CIsco swithces
> 
> Hi, did enabling "ip ssh password-auth" solved the problem?

For me yes.

**Comment by tfaxes** [comment]
Any progress on this? Getting the same error on an SG-300 even with ip ssh password-auth enabled.

**Comment by FilipFabicevic** [comment]
> Any progress on this? Getting the same error on an SG-300 even with ip ssh password-auth enabled.

ip ssh server
ip ssh password-auth
ip ssh pubkey-auth auto-login

Do you have this enabled on the CBS switches.

**Comment by qaxi** [comment]
It seems as configuration prohlem on Cisco switch. I wrote additional paragraphs to README.txt to clarify necessary configuration nedded.
