### ISSUE TITLE
Collection Requirements Violation - Semantic Versioning

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.ciscosmb#75]
##### SUMMARY
According to the changelog (https://github.com/ansible-collections/community.ciscosmb/blob/main/CHANGELOG.rst#v108), the bugfix 1.0.8 release contains a **breaking change**. This is explicitly prohibited by semantic versioning (https://semver.org/) - breaking changes **must** happen in new major versions.

Semantic versioning is one of the main collection requirements for inclusion in Ansible (https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#versioning-and-deprecation).

In today's Ansible 9.5.0 release, we pinned community.ciscosmb to <1.0.8 to avoid breaking changes.

Please amend this breaking change and create a new 1.0.9 bugfix release without it as soon as possible, or risk freezing community.ciscosmb to 1.0.8 for the remainder of the Ansible 9 release cycle.

The breaking change was introduced here: https://github.com/ansible-collections/community.ciscosmb/pull/72 Better return both the old (misspelled) and the new fact until the next major release, and declare the misspelled one as deprecated.

Please also note that according to semver, deprecations have to happen in minor version releases, not in bugfix verison releases. So 1.0.9 should add the misspelled fact back, and 1.1.0 should deprecate the misspelled fact name.

##### ISSUE TYPE
- Bug Report

**Comment by qaxi** [comment]
Proposing close this issue. It is Solved by #76 

Published release 1.0.9

Primarily revert release. Previous release (1.0.8) fixed typo in attribute name, but it was breaking change.
  This release brought the typo back (bandwith) and just added the new attribute with correct name "bandwidth" as a copy of the mistypped attribute.

  Attribude "bandwith" will be removed in next minor release.

**Comment by felixfontein** [comment]
Thanks for fixing this! One note: in the announcement you wrote `Attribude "bandwith" will be removed in next minor release.` - this should be "in next major release", since removals must not happen in minor releases according to semantic versioning.
